import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import image from '../images/capybara.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Capybara Organizer",

  description: "Generated by create next app",

  icons: {
    icon:[
      '/favicon.ico',
    ],
    apple:[
      '/apple-touch-icon.png'
    ],
    shortcut:[
      '/apple-touch-icon.png',
    ]
  },
  manifest: '/site.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
