services:
  # Serviço para a API Express
  backend:
    build: ./back
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-8080}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - database

  # Serviço para o banco de dados PostgreSQL
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dbname}
    volumes:
      - pgdata:/var/lib/postgresql

  # Serviço para o front-end Next.js
  frontend:
    build: ./front
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    depends_on:
      - backend

volumes:
  pgdata:
